### PR TITLE
Allow several sst impl

### PR DESCRIPTION
**Pull request by mirahbo**

### CODE REVIEW

**Comment by mirahbo** [comment]
I'm going to propose a PR to allow using several implementations of the SST:
- H2 store (from this repository)
- LRU Cache (from monotiorjbl repository)

Why? We favor this repository to be able to process OOXML files. For huge files with only distinct values, the SST is quite huge. We made a profiling and we figured out that querying the H2 datastore took too much time. For this type of file, a LRU cache implementation for the SST seems more fit.

I wanted to open a draft PR in my own fork, but I opened it here by mistake. Sorry for the inconvenience.

**Comment by pjfanning** [comment]
@mirahbo would it be possible for you to but the SST implementation in its own jar? Then it would be possible for this excel-streaming-reader implementation to offer it as an option?

With the monitorjbl project, I had been contributing fixes directly to the main project and I only forked the projects when the monitorjbl project stopped doing regular merges. If we end up with many forks then it will be hard for users to find the fork that has all the features they want. One fork could have recent bug fixes while another less maintained fork may have a good feature.

**Comment by mirahbo** [comment]
Yes, sure, I would rather keep your fork instead of creating another one. The LRU cache implementation can be put in its own jar and be used as an option. In that case, the H2 store implementation of the SST would be the default and the source code would remain in this repository?

**Comment by pjfanning** [comment]
My SST is in https://github.com/pjfanning/poi-shared-strings - I can import other jars in a similar way. If you like, I could even add your SST there so that there aren't extra jars floating around. excel-streaming-reader could allow users to choose which SST to use.

**Comment by mirahbo** [comment]
That's a good idea. It might be easier to put the SST in poi-shared-strings for now.

I'm going to open two PR, then: in excel-streaming-reader and in poi-shared-strings. I won't propose any breaking change for now. I agree that the other SST should only be an extra-option.

Ultimately, it will be up to you to accept any change I'm going to propose.

**Pull request closed without merging**
